# Generated by Django 3.2.7 on 2021-09-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0002_auto_20210905_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='time',
            new_name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ballance',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=8000),
        ),
    ]
