# Generated by Django 3.2.7 on 2021-09-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0003_auto_20210920_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient',
            new_name='reciever',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=1000000000),
        ),
    ]
